---

- name: Install Nginx site config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/sample-appliance.conf
  register: nginx_conf

- name: Restart Nginx if required
  service:
    name: nginx
    state: restarted
  when: nginx_conf is changed
