---
# Provision the infrastructure
# The CaaS puts hosts for accessing the OpenStack API into the 'openstack' group
- name: Provision the infrastructure
  hosts: openstack
  roles:
    - cluster_infra

# All the hosts get Nginx
# need to set a version for Nginx
- name: Install Nginx
  hosts: cluster
  become: true
  roles:
    - nginx_install

# Configure the backends
- name: Configure backends
- hosts: backends
  become: true
  roles:
    - backend

# Configure the load-balancer
- name: Configure load-balancer
  hosts: load_balancers
  become: true
  roles:
    - load_balancer

# Write the outputs as the final task
- name: Write outputs
  hosts: localhost
  tasks:
    - ansible.builtin.debug:
        var: outputs
      vars:
        outputs:
          cluster_access_ip: "{{ hostvars[groups['openstack'][0]].cluster_gateway_ip }}"
