---
- name: Ensure HTML directory exists
  ansible.builtin.file:
    path: /opt/sample-appliance/html
    state: directory
    mode: '0755'

- name: Install HTML index file
  ansible.builtin.template:
    src: index.html.j2
    dest: /opt/sample-appliance/html/index.html
    mode: '0644'
  register: backend_html_index

- name: Install Nginx site config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/sample-appliance.conf
    mode: '0644'
  register: backend_nginx_conf

- name: Restart Nginx if required
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: backend_html_index is changed or backend_nginx_conf is changed
