---

- name: Ensure HTML directory exists
  file:
    path: /opt/sample-appliance/html
    state: directory

- name: Install HTML index file
  template:
    src: index.html.j2
    dest: /opt/sample-appliance/html/index.html
  register: html_index

- name: Install Nginx site config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/sample-appliance.conf
  register: nginx_conf

- name: Restart Nginx if required
  service:
    name: nginx
    state: restarted
  when: html_index is changed or nginx_conf is changed
